package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"sort"
	"strings"

	"github.com/xela-io/xelanote/internal/db"
	"github.com/xela-io/xelanote/internal/llm"
)

// Token budget constants for recipe prompts.
const (
	MaxRecipesForPrompt = 100
	TokensPerRecipe     = 150
	MaxSnippetLength    = 200
)

// Model-specific token budgets for the recipe list portion of prompts.
var modelTokenBudgets = map[string]int{
	"claude": 15000,
	"gemini": 12000,
}

// SimilarRecipeResult represents a single similar recipe found by the LLM.
type SimilarRecipeResult struct {
	NoteID          string  `json:"note_id"`
	Title           string  `json:"title"`
	SimilarityScore float64 `json:"similarity_score"`
	Reason          string  `json:"reason"`
}

// IngredientMatchResult represents a recipe that matches given ingredients.
type IngredientMatchResult struct {
	NoteID             string   `json:"note_id"`
	Title              string   `json:"title"`
	MatchScore         float64  `json:"match_score"`
	MatchedIngredients []string `json:"matched_ingredients"`
	MissingIngredients []string `json:"missing_ingredients"`
}

// GeneratedRecipe represents a recipe generated by the LLM.
type GeneratedRecipe struct {
	Title           string                `json:"title"`
	Servings        int                   `json:"servings"`
	PrepTimeMinutes *int                  `json:"prep_time_minutes"`
	CookTimeMinutes *int                  `json:"cook_time_minutes"`
	Difficulty      *string               `json:"difficulty"`
	Ingredients     []GeneratedIngredient `json:"ingredients"`
	Instructions    string                `json:"instructions"`
}

// GeneratedIngredient represents an ingredient in a generated recipe.
type GeneratedIngredient struct {
	Name     string   `json:"name"`
	Amount   *float64 `json:"amount"`
	Unit     *string  `json:"unit"`
	Scalable bool     `json:"scalable"`
	Optional bool     `json:"optional"`
}

// IngredientSuggestionResult combines matches and generated recipes.
type IngredientSuggestionResult struct {
	Matches   []IngredientMatchResult `json:"matches"`
	Generated []GeneratedRecipe       `json:"generated"`
}

// RecipeSuggestionService handles AI-powered recipe suggestions.
type RecipeSuggestionService struct {
	db     *db.DB
	router *llm.ProviderRouter
	recipe *RecipeService
	logger *slog.Logger
}

// NewRecipeSuggestionService creates a new RecipeSuggestionService.
func NewRecipeSuggestionService(database *db.DB, router *llm.ProviderRouter, recipeService *RecipeService) *RecipeSuggestionService {
	return &RecipeSuggestionService{
		db:     database,
		router: router,
		recipe: recipeService,
		logger: slog.Default(),
	}
}

// FindSimilarRecipes finds recipes similar to the given recipe using LLM.
func (s *RecipeSuggestionService) FindSimilarRecipes(
	ctx context.Context, userID int, noteID string,
	collectionID *int, locale string,
) ([]SimilarRecipeResult, error) {
	locale = normalizeLocale(locale)

	// Get provider
	provider, err := s.router.GetAnyProvider(ctx, userID)
	if err != nil {
		return nil, err
	}

	// Load current recipe detail
	detail, err := s.recipe.GetRecipeDetail(userID, noteID)
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe detail: %w", err)
	}
	if detail.Encrypted {
		return nil, ErrRecipeEncrypted
	}

	// Build current recipe context
	currentIngNames := make([]string, 0, len(detail.Ingredients))
	for _, ing := range detail.Ingredients {
		currentIngNames = append(currentIngNames, ing.Name)
	}
	var difficulty *string
	if detail.Metadata != nil {
		difficulty = detail.Metadata.Difficulty
	}
	current := llm.RecipeContext{
		NoteID:          noteID,
		Title:           detail.Note.Title,
		IngredientNames: currentIngNames,
		ContentSnippet:  truncate(detail.Note.Content, MaxSnippetLength),
		Difficulty:      difficulty,
	}

	// Load candidate summaries
	snippetLen := computeSnippetLength(provider.Name())
	var summaries []db.RecipeSummary
	if collectionID != nil {
		summaries, err = s.db.GetRecipeSummariesInCollection(userID, *collectionID, snippetLen)
	} else {
		summaries, err = s.db.GetRecipeSummaries(userID, snippetLen)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe summaries: %w", err)
	}

	// Remove current recipe from candidates (service-level self-match exclusion)
	candidates := make([]db.RecipeSummary, 0, len(summaries))
	for _, s := range summaries {
		if s.NoteID != noteID {
			candidates = append(candidates, s)
		}
	}

	if len(candidates) < 2 {
		return []SimilarRecipeResult{}, nil
	}

	// Pre-filter if too many candidates
	if len(candidates) > MaxRecipesForPrompt {
		candidates = preFilterByJaccard(candidates, currentIngNames, MaxRecipesForPrompt)
	}

	// Build prompt contexts
	promptCandidates := make([]llm.RecipeContext, len(candidates))
	for i, c := range candidates {
		promptCandidates[i] = llm.RecipeContext{
			NoteID:          c.NoteID,
			Title:           c.Title,
			IngredientNames: c.IngredientNames,
			ContentSnippet:  c.ContentSnippet,
			Difficulty:      c.Difficulty,
			Servings:        c.Servings,
		}
	}

	prompt := llm.BuildSimilarRecipePrompt(current, promptCandidates, locale)

	response, err := provider.Generate(ctx, prompt, 2000)
	if err != nil {
		return nil, fmt.Errorf("LLM generation failed: %w", err)
	}

	// Parse JSON response
	var results []SimilarRecipeResult
	if err := json.Unmarshal([]byte(cleanJSONResponse(response)), &results); err != nil {
		return nil, fmt.Errorf("failed to parse LLM response: %w", err)
	}

	// Validate note_ids exist in our candidate set
	candidateIDs := make(map[string]bool, len(candidates))
	for _, c := range candidates {
		candidateIDs[c.NoteID] = true
	}
	validated := make([]SimilarRecipeResult, 0, len(results))
	for _, r := range results {
		if candidateIDs[r.NoteID] && r.NoteID != noteID {
			validated = append(validated, r)
		}
	}

	return validated, nil
}

// SuggestByIngredients finds matching recipes and generates new ideas based on ingredients.
func (s *RecipeSuggestionService) SuggestByIngredients(
	ctx context.Context, userID int, ingredients []string,
	collectionID *int, locale string,
) (*IngredientSuggestionResult, error) {
	locale = normalizeLocale(locale)

	provider, err := s.router.GetAnyProvider(ctx, userID)
	if err != nil {
		return nil, err
	}

	// Load summaries
	snippetLen := computeSnippetLength(provider.Name())
	var summaries []db.RecipeSummary
	if collectionID != nil {
		summaries, err = s.db.GetRecipeSummariesInCollection(userID, *collectionID, snippetLen)
	} else {
		summaries, err = s.db.GetRecipeSummaries(userID, snippetLen)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe summaries: %w", err)
	}

	result := &IngredientSuggestionResult{
		Matches:   []IngredientMatchResult{},
		Generated: []GeneratedRecipe{},
	}

	// Step 1: Find matching existing recipes (if any exist)
	if len(summaries) > 0 {
		if len(summaries) > MaxRecipesForPrompt {
			summaries = preFilterByJaccard(summaries, ingredients, MaxRecipesForPrompt)
		}

		promptRecipes := make([]llm.RecipeContext, len(summaries))
		for i, s := range summaries {
			promptRecipes[i] = llm.RecipeContext{
				NoteID:          s.NoteID,
				Title:           s.Title,
				IngredientNames: s.IngredientNames,
				ContentSnippet:  s.ContentSnippet,
				Difficulty:      s.Difficulty,
				Servings:        s.Servings,
			}
		}

		matchPrompt := llm.BuildIngredientMatchPrompt(ingredients, promptRecipes, locale)
		matchResp, err := provider.Generate(ctx, matchPrompt, 2000)
		if err != nil {
			s.logger.Warn("ingredient match LLM call failed", slog.String("error", err.Error()))
		} else {
			var matches []IngredientMatchResult
			if err := json.Unmarshal([]byte(cleanJSONResponse(matchResp)), &matches); err != nil {
				s.logger.Warn("failed to parse ingredient match response", slog.String("error", err.Error()))
			} else {
				// Validate note_ids
				summaryIDs := make(map[string]bool, len(summaries))
				for _, sm := range summaries {
					summaryIDs[sm.NoteID] = true
				}
				for _, m := range matches {
					if summaryIDs[m.NoteID] {
						result.Matches = append(result.Matches, m)
					}
				}
			}
		}
	}

	// Step 2: Generate new recipe ideas
	existingTitles := make([]string, 0, len(summaries))
	for _, sm := range summaries {
		existingTitles = append(existingTitles, sm.Title)
	}

	genPrompt := llm.BuildRecipeGenerationPrompt(ingredients, existingTitles, locale)
	genResp, err := provider.Generate(ctx, genPrompt, 4000)
	if err != nil {
		s.logger.Warn("recipe generation LLM call failed", slog.String("error", err.Error()))
	} else {
		var genResult struct {
			Recipes []GeneratedRecipe `json:"recipes"`
		}
		if err := json.Unmarshal([]byte(cleanJSONResponse(genResp)), &genResult); err != nil {
			s.logger.Warn("failed to parse generated recipes", slog.String("error", err.Error()))
		} else {
			for i := range genResult.Recipes {
				validateGeneratedRecipe(&genResult.Recipes[i])
			}
			result.Generated = genResult.Recipes
		}
	}

	return result, nil
}

// ExtractIngredientsFromPhoto uses a vision model to identify ingredients in a photo.
func (s *RecipeSuggestionService) ExtractIngredientsFromPhoto(
	ctx context.Context, userID int,
	imageData []byte, mimeType string, locale string,
) ([]string, error) {
	locale = normalizeLocale(locale)

	visionProvider, err := s.router.GetVisionProvider(ctx, userID)
	if err != nil {
		if errors.Is(err, llm.ErrVisionNotAvailable) {
			return nil, err
		}
		return nil, fmt.Errorf("failed to get vision provider: %w", err)
	}

	prompt := llm.BuildFridgePhotoPrompt(locale)
	response, err := visionProvider.GenerateWithImage(ctx, prompt, imageData, mimeType, 1000)
	if err != nil {
		return nil, fmt.Errorf("vision API call failed: %w", err)
	}

	var ingredients []string
	if err := json.Unmarshal([]byte(cleanJSONResponse(response)), &ingredients); err != nil {
		return nil, fmt.Errorf("failed to parse vision response: %w", err)
	}

	return ingredients, nil
}

// SaveGeneratedRecipe saves a generated recipe as a new note with metadata and ingredients.
func (s *RecipeSuggestionService) SaveGeneratedRecipe(
	userID int, req SaveGeneratedRecipeRequest,
) (*db.Note, error) {
	if strings.TrimSpace(req.Title) == "" {
		return nil, fmt.Errorf("title is required")
	}
	if strings.TrimSpace(req.Instructions) == "" {
		return nil, fmt.Errorf("instructions are required")
	}
	if req.Servings < 1 {
		req.Servings = 4
	}
	if req.Servings > 999 {
		req.Servings = 999
	}
	if req.FolderPath == "" {
		req.FolderPath = "/Rezepte"
	}

	// Validate difficulty
	if req.Difficulty != nil {
		d := *req.Difficulty
		if d != "easy" && d != "medium" && d != "hard" {
			req.Difficulty = nil
		}
	}

	metadata := db.RecipeMetadata{
		Servings:        req.Servings,
		PrepTimeMinutes: req.PrepTimeMinutes,
		CookTimeMinutes: req.CookTimeMinutes,
		Difficulty:      req.Difficulty,
	}

	ingredients := make([]db.RecipeIngredient, 0, len(req.Ingredients))
	for _, ing := range req.Ingredients {
		name := strings.TrimSpace(ing.Name)
		if name == "" {
			continue
		}
		ingredients = append(ingredients, db.RecipeIngredient{
			Name:     name,
			Amount:   ing.Amount,
			Unit:     ing.Unit,
			Optional: ing.Optional,
			Scalable: ing.Scalable,
		})
	}

	return s.db.CreateRecipeNoteWithIngredients(
		userID, req.Title, req.Instructions, req.FolderPath,
		metadata, ingredients,
	)
}

// SaveGeneratedRecipeRequest is the input for saving a generated recipe.
type SaveGeneratedRecipeRequest struct {
	Title           string                `json:"title"`
	Instructions    string                `json:"instructions"`
	Servings        int                   `json:"servings"`
	PrepTimeMinutes *int                  `json:"prep_time_minutes"`
	CookTimeMinutes *int                  `json:"cook_time_minutes"`
	Difficulty      *string               `json:"difficulty"`
	Ingredients     []GeneratedIngredient `json:"ingredients"`
	FolderPath      string                `json:"folder_path"`
}

// --- Helper functions ---

func normalizeLocale(locale string) string {
	if locale == "de" {
		return "de"
	}
	return "en"
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}

func computeSnippetLength(providerName string) int {
	budget, ok := modelTokenBudgets[providerName]
	if !ok {
		budget = 10000
	}
	perRecipe := budget / MaxRecipesForPrompt
	// ~4 chars per token, subtract typical title+ingredients length (~100 chars)
	snippetLen := perRecipe*4 - 100
	if snippetLen < 50 {
		snippetLen = 50
	}
	if snippetLen > MaxSnippetLength {
		snippetLen = MaxSnippetLength
	}
	return snippetLen
}

// preFilterByJaccard selects the top-N candidates by Jaccard similarity on ingredient names.
func preFilterByJaccard(candidates []db.RecipeSummary, targetIngredients []string, limit int) []db.RecipeSummary {
	targetSet := make(map[string]bool, len(targetIngredients))
	for _, ing := range targetIngredients {
		targetSet[strings.ToLower(strings.TrimSpace(ing))] = true
	}

	type scored struct {
		index int
		score float64
	}

	scores := make([]scored, len(candidates))
	for i, c := range candidates {
		candSet := make(map[string]bool, len(c.IngredientNames))
		for _, ing := range c.IngredientNames {
			candSet[strings.ToLower(strings.TrimSpace(ing))] = true
		}

		intersection := 0
		for k := range targetSet {
			if candSet[k] {
				intersection++
			}
		}

		union := len(targetSet) + len(candSet) - intersection
		score := 0.0
		if union > 0 {
			score = float64(intersection) / float64(union)
		}
		scores[i] = scored{index: i, score: score}
	}

	sort.Slice(scores, func(a, b int) bool {
		return scores[a].score > scores[b].score
	})

	result := make([]db.RecipeSummary, 0, limit)
	for i := 0; i < limit && i < len(scores); i++ {
		result = append(result, candidates[scores[i].index])
	}
	return result
}

// validateGeneratedRecipe corrects/clamps values from LLM output.
func validateGeneratedRecipe(r *GeneratedRecipe) {
	if r.Servings < 1 {
		r.Servings = 4
	}
	if r.Servings > 999 {
		r.Servings = 999
	}
	if r.Difficulty != nil {
		d := *r.Difficulty
		if d != "easy" && d != "medium" && d != "hard" {
			r.Difficulty = nil
		}
	}
	for i := range r.Ingredients {
		r.Ingredients[i].Name = strings.TrimSpace(r.Ingredients[i].Name)
		if len(r.Ingredients[i].Name) > 200 {
			r.Ingredients[i].Name = r.Ingredients[i].Name[:200]
		}
		if r.Ingredients[i].Unit != nil {
			trimmed := strings.TrimSpace(*r.Ingredients[i].Unit)
			if len(trimmed) > 50 {
				trimmed = trimmed[:50]
			}
			r.Ingredients[i].Unit = &trimmed
		}
	}
}

// cleanJSONResponse strips markdown code blocks that LLMs sometimes add.
func cleanJSONResponse(s string) string {
	s = strings.TrimSpace(s)
	if strings.HasPrefix(s, "```json") {
		s = strings.TrimPrefix(s, "```json")
	} else if strings.HasPrefix(s, "```") {
		s = strings.TrimPrefix(s, "```")
	}
	if strings.HasSuffix(s, "```") {
		s = strings.TrimSuffix(s, "```")
	}
	return strings.TrimSpace(s)
}
