package service

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/xela-io/xelanote/internal/cache"
	"github.com/xela-io/xelanote/internal/db"
	"github.com/xela-io/xelanote/internal/llm"
)

// Token budget constants for recipe prompts.
const (
	MaxRecipesForPrompt = 100
	TokensPerRecipe     = 150
	MaxSnippetLength    = 200
)

// Model-specific token budgets for the recipe list portion of prompts.
var modelTokenBudgets = map[string]int{
	"claude": 15000,
	"gemini": 12000,
}

var ErrNoRecipeFound = errors.New("no recipe found")

// SimilarRecipeResult represents a single similar recipe found by the LLM.
type SimilarRecipeResult struct {
	NoteID          string  `json:"note_id"`
	Title           string  `json:"title"`
	SimilarityScore float64 `json:"similarity_score"`
	Reason          string  `json:"reason"`
}

// IngredientMatchResult represents a recipe that matches given ingredients.
type IngredientMatchResult struct {
	NoteID             string   `json:"note_id"`
	Title              string   `json:"title"`
	MatchScore         float64  `json:"match_score"`
	MatchedIngredients []string `json:"matched_ingredients"`
	MissingIngredients []string `json:"missing_ingredients"`
}

// GeneratedRecipe represents a recipe generated by the LLM.
type GeneratedRecipe struct {
	Title           string                `json:"title"`
	Servings        int                   `json:"servings"`
	PrepTimeMinutes *int                  `json:"prep_time_minutes"`
	CookTimeMinutes *int                  `json:"cook_time_minutes"`
	Difficulty      *string               `json:"difficulty"`
	SourceURL       *string               `json:"source_url,omitempty"`
	Ingredients     []GeneratedIngredient `json:"ingredients"`
	Instructions    string                `json:"instructions"`
}

// GeneratedIngredient represents an ingredient in a generated recipe.
type GeneratedIngredient struct {
	Name      string   `json:"name"`
	Amount    *float64 `json:"amount"`
	Unit      *string  `json:"unit"`
	GroupName *string  `json:"group_name,omitempty"`
	Scalable  bool     `json:"scalable"`
	Optional  bool     `json:"optional"`
}

// IngredientSuggestionResult combines matches and generated recipes.
type IngredientSuggestionResult struct {
	Matches   []IngredientMatchResult `json:"matches"`
	Generated []GeneratedRecipe       `json:"generated"`
}

// Cache key prefix for recipe suggestion lookups.
const recipeSummaryCachePrefix = "cache:recipe:summaries:"

// RecipeSuggestionService handles AI-powered recipe suggestions.
type RecipeSuggestionService struct {
	db     *db.DB
	router *llm.ProviderRouter
	recipe *RecipeService
	logger *slog.Logger
	cache  *cache.Cache
}

// NewRecipeSuggestionService creates a new RecipeSuggestionService.
func NewRecipeSuggestionService(database *db.DB, router *llm.ProviderRouter, recipeService *RecipeService) *RecipeSuggestionService {
	return &RecipeSuggestionService{
		db:     database,
		router: router,
		recipe: recipeService,
		logger: slog.Default(),
		cache:  cache.New(10 * time.Minute), // 10 minute TTL for recipe summaries
	}
}

// Close releases background resources held by the service.
func (s *RecipeSuggestionService) Close() {
	if s.cache != nil {
		s.cache.Close()
	}
}

// getRecipeSummaries returns cached recipe summaries for a user.
// The snippetLen parameter is included in the cache key because different
// LLM providers request different snippet lengths.
func (s *RecipeSuggestionService) getRecipeSummaries(userID, snippetLen int) ([]db.RecipeSummary, error) {
	cacheKey := fmt.Sprintf("%s%d:%d", recipeSummaryCachePrefix, userID, snippetLen)
	if cached, ok := s.cache.Get(cacheKey); ok {
		return cached.([]db.RecipeSummary), nil
	}

	summaries, err := s.db.GetRecipeSummaries(userID, snippetLen)
	if err != nil {
		return nil, err
	}

	s.cache.Set(cacheKey, summaries)
	return summaries, nil
}

// getRecipeSummariesInCollection returns cached recipe summaries for a collection.
func (s *RecipeSuggestionService) getRecipeSummariesInCollection(userID, collectionID, snippetLen int) ([]db.RecipeSummary, error) {
	cacheKey := fmt.Sprintf("%s%d:col:%d:%d", recipeSummaryCachePrefix, userID, collectionID, snippetLen)
	if cached, ok := s.cache.Get(cacheKey); ok {
		return cached.([]db.RecipeSummary), nil
	}

	summaries, err := s.db.GetRecipeSummariesInCollection(userID, collectionID, snippetLen)
	if err != nil {
		return nil, err
	}

	s.cache.Set(cacheKey, summaries)
	return summaries, nil
}

// invalidateRecipeSummaryCache clears cached summaries for a user.
func (s *RecipeSuggestionService) invalidateRecipeSummaryCache(userID int) {
	s.cache.DeleteByPrefix(fmt.Sprintf("%s%d:", recipeSummaryCachePrefix, userID))
}

// SuggestByIngredients finds matching recipes and generates new ideas based on ingredients.
func (s *RecipeSuggestionService) SuggestByIngredients(
	ctx context.Context, userID int, ingredients []string,
	collectionID *int, locale string,
) (*IngredientSuggestionResult, error) {
	locale = normalizeLocale(locale)

	provider, err := s.router.GetAnyProvider(ctx, userID)
	if err != nil {
		return nil, err
	}

	// Load summaries (cached)
	snippetLen := computeSnippetLength(provider.Name())
	var summaries []db.RecipeSummary
	if collectionID != nil {
		summaries, err = s.getRecipeSummariesInCollection(userID, *collectionID, snippetLen)
	} else {
		summaries, err = s.getRecipeSummaries(userID, snippetLen)
	}
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe summaries: %w", err)
	}

	// Load dietary preference (graceful fallback to "none")
	dietaryPref, err := s.db.GetDietaryPreference(userID)
	if err != nil {
		s.logger.Warn("failed to load dietary preference, using default", slog.String("error", err.Error()))
		dietaryPref = "none"
	}

	result := &IngredientSuggestionResult{
		Matches:   []IngredientMatchResult{},
		Generated: []GeneratedRecipe{},
	}

	// Step 1: Find matching existing recipes (if any exist)
	if len(summaries) > 0 {
		if len(summaries) > MaxRecipesForPrompt {
			summaries = preFilterByJaccard(summaries, ingredients, MaxRecipesForPrompt)
		}

		promptRecipes := make([]llm.RecipeContext, len(summaries))
		for i, s := range summaries {
			promptRecipes[i] = llm.RecipeContext{
				NoteID:          s.NoteID,
				Title:           s.Title,
				IngredientNames: s.IngredientNames,
				ContentSnippet:  s.ContentSnippet,
				Difficulty:      s.Difficulty,
				Servings:        s.Servings,
			}
		}

		matchPrompt := llm.BuildIngredientMatchPrompt(ingredients, promptRecipes, locale, dietaryPref)
		matchResp, err := provider.Generate(ctx, matchPrompt, 2000)
		if err != nil {
			s.logger.Warn("ingredient match LLM call failed", slog.String("error", err.Error()))
		} else {
			var matches []IngredientMatchResult
			if err := json.Unmarshal([]byte(llm.CleanMarkdownCodeBlock(matchResp)), &matches); err != nil {
				s.logger.Warn("failed to parse ingredient match response", slog.String("error", err.Error()))
			} else {
				// Validate note_ids
				summaryIDs := make(map[string]bool, len(summaries))
				for _, sm := range summaries {
					summaryIDs[sm.NoteID] = true
				}
				for _, m := range matches {
					if summaryIDs[m.NoteID] {
						result.Matches = append(result.Matches, m)
					}
				}
			}
		}
	}

	// Step 2: Generate new recipe ideas
	existingTitles := make([]string, 0, len(summaries))
	for _, sm := range summaries {
		existingTitles = append(existingTitles, sm.Title)
	}

	genPrompt := llm.BuildRecipeGenerationPrompt(ingredients, existingTitles, locale, dietaryPref)
	genResp, err := provider.Generate(ctx, genPrompt, 4000)
	if err != nil {
		s.logger.Warn("recipe generation LLM call failed", slog.String("error", err.Error()))
	} else {
		var genResult struct {
			Recipes []GeneratedRecipe `json:"recipes"`
		}
		if err := json.Unmarshal([]byte(llm.CleanMarkdownCodeBlock(genResp)), &genResult); err != nil {
			s.logger.Warn("failed to parse generated recipes", slog.String("error", err.Error()))
		} else {
			for i := range genResult.Recipes {
				validateGeneratedRecipe(&genResult.Recipes[i])
			}
			result.Generated = genResult.Recipes
		}
	}

	return result, nil
}

// --- Shared helper functions ---

func normalizeLocale(locale string) string {
	if locale == "de" {
		return "de"
	}
	return "en"
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}

func computeSnippetLength(providerName string) int {
	budget, ok := modelTokenBudgets[providerName]
	if !ok {
		budget = 10000
	}
	perRecipe := budget / MaxRecipesForPrompt
	// ~4 chars per token, subtract typical title+ingredients length (~100 chars)
	snippetLen := perRecipe*4 - 100
	if snippetLen < 50 {
		snippetLen = 50
	}
	if snippetLen > MaxSnippetLength {
		snippetLen = MaxSnippetLength
	}
	return snippetLen
}
